### ISSUE TITLE
Membership maintenance check

### ISSUE THREAD

**Issue by ibdafna** [jupyter-widgets/team-compass#28]
Hey team,

We have grown a lot over the last couple of years, and as we're nearing towards the end of 2023, now is a good time to trigger a [membership maintenance check](https://jupyter-foundations-and-standards.readthedocs.io/en/latest/team/becoming-member.html#membership-maintenance).

Please indicate below, one way or another, if you would like to remain an active member of the Jupyter Widgets Council, or if you prefer to become inactive.

This poll will remain open until the **first week of January, 2024**, at which point we will assume an `inactive` role for anyone not participating.

- [x] Maarten Breddels
- [x] David Brochart
- [x] Sylvain Corlay
- [x] Matt Craig
- [x] Itay Dafna
- [x] Vidar Tonaas Fauske
- [x] Jason Grout
- [x] Paul Ivanov
- [ ] Mariana Meireles
- [x] Jeremy Tuloup
- [x] Martin Renou

cc @jupyter-widgets/jupyter-widgets-council

**Comment by davidbrochart** [comment]
I'd like to remain an active member of the Jupyter Widgets Council (I cannot check the box above).

**Comment by ivanov** [comment]
same with me - I'd like to remain active and cannot check the box above. @ibdafna can you add https://github.com/orgs/jupyter-widgets/teams/jupyter-widgets-council team as an owner to this repo, I think that'll fix it for all of us.

**Comment by ibdafna** [comment]
@ivanov I don't seem to have permissions to do that. @jasongrout can you either add me as a full admin for the jupyter-widgets org or add the jupyter-widgets-council team as an owner of this repo? @ivanov @davidbrochart I'll tick the box for you in the meantime. Anyone else who can't tick the box comment here and I'll tick it for you.

**Comment by ivanov** [comment]
Thank you, Itay `TBaaS` Dafna  - ticking boxes as a service!  ;)

**Comment by mwcraig** [comment]
I just finished my last full-time semester of teaching so I'm looking forward to being able to be involved more in the future 😀

**Comment by jasongrout** [comment]
> @jasongrout can you either add me as a full admin for the jupyter-widgets org or add the jupyter-widgets-council team as an owner of this repo?

Done!

**Comment by marimeireles** [comment]
Hi folks, I have been kind of out of the Jupyter ecosystem lately so it doesn't really make sense for me to continue maintaining.
However, if you think there's something I might help, don't hesitate to ping me! ❤️

**Comment by ibdafna** [comment]
Concluding this survey - it's great to see almost everyone electing to remain active!
