### ISSUE TITLE
2024 Jupyter Widgets Dev Meetings

### ISSUE THREAD

**Issue by kolibril13** [jupyter-widgets/team-compass#29]
Will there be Jupyter Widgets Dev Meetings in 2024? cc. @ibdafna 
If so, I'd be glad to be there!
Follow-up to https://github.com/jupyter-widgets/team-compass/issues/19

**Comment by ibdafna** [comment]
@kolibril13 we had quite low attendance in 2023, and so for 2024 we'll need to figure out a new time slot where most maintainers can attend. We'll update once that has been decided.

**Comment by SylvainCorlay** [comment]
Closing as we have a biweekly in place!
