### ISSUE TITLE
New weekly ipywidgets meeting time

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/team-compass#9]
In the last few meetings, we've decided to have weekly meetings instead of every-two-weeks, and reevaluate our weekly meeting time (7am Pacific). Here is a new poll. If you would like to join the meeting, please indicate what times you are available to make it.

 http://whenisgood.net/nx49zs8

**Comment by jasongrout** [comment]
I'll close the poll Sunday Apr 4 (Anywhere on Earth) so we can pick a meeting time for next week.

**Comment by jasongrout** [comment]
Also, with the existing replies, we already do not have a meeting time that fits everyone. Please be generous with your availability to help accommodate people across many timezones.

**Comment by jtpio** [comment]
We discussed the new time at the meeting today and based on the results concluded that Tuesdays at 09:00 a.m. would be a good option: https://github.com/jupyter-widgets/team-compass/issues/1#issuecomment-815883301

However looking at the Jupyter Community Calendar there seems to be the `nteract` call at the same time: https://discourse.jupyter.org/t/jupyter-community-calendar/2485

Meeting details for the `nteract` call point to a Google Meet link, so both the `ipywidgets` and the `nteract` meetings could technically overlap (with the `ipywidgets` call happening on Zoom)

**Comment by willingc** [comment]
@jtpio Yes, the ipywidgets and nteract meetings will overlap. nteract uses jitsi now so there isn't a resource conflict just a time conflict.

I'm assuming the widgets calls will be recorded.

**Comment by jtpio** [comment]
If the nteract meeting is 30 minutes long (as shown in the jupyter community calendar), then one option could be to move the widgets meeting to 09:30 am Pacific, so there is no overlap.

And maybe the widgets meeting could then be 30 minutes long instead of 1 hour.

**Comment by ibdafna** [comment]
9.30 PST works for me! 👍

**Comment by vidartf** [comment]
9.30 Tuesdays should work well. Let's make it official, and also try to get it in the community calendar? Either way, let's try to get our heads together next week :)

**Comment by ilyabo** [comment]
So when is the next one?

**Comment by jtpio** [comment]
@ilyabo it will be on Tuesday 27 April at 09:30 am Pacific time.

More info in https://github.com/jupyter-widgets/team-compass#weekly-team-meetings (zoom link and meeting notes).

**Comment by jtpio** [comment]
@vidartf @willingc would it be possible to update the Jupyter Calendar with the new time, if you have access to it?

https://jupyter.readthedocs.io/en/latest/community/content-community.html#jupyter-community-meetings

Thanks!

**Comment by willingc** [comment]
@jtpio Sorry, I don't have access to the calendar. Perhaps one of the JupyterLab folks do.
